my_data:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost
      user: mydata
      password: postgres
      port: 5432
      dbname: mydata
      schema: mydata
      threads: 1
