version: '3.7'
services:
  postgres:
    image: postgres:14.2
    restart: always
    environment:
      - POSTGRES_USER=mydata
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=mydata
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '5432:5432'
    volumes:
      # copy the sql script to create tables
      - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql

